//! Virtual cursor management for the Server.
//!
//! Tracks the global cursor position based on raw evdev deltas.
//! Detects when the cursor crosses screen boundaries.

use crate::boundary::{CoordinateSystem, ScreenInfo};

/// Events generated by virtual cursor boundary detection.
#[derive(Debug, Clone)]
pub enum BoundaryEvent {
    /// Cursor entered a different screen.
    /// Contains the target screen ID and the entry position in that screen's local coordinates.
    Enter {
        target_screen: u8,
        enter_x: f32,
        enter_y: f32,
    },
    /// Cursor left the current screen and returned to the server screen.
    Leave {
        source_screen: u8,
    },
}

/// Virtual cursor state on the Server.
///
/// Maintains the cursor position in global coordinates, updated by raw evdev deltas.
/// Detects when the cursor crosses screen boundaries.
pub struct VirtualCursor {
    /// Global X position (across all screens).
    pub global_x: f64,
    /// Global Y position.
    pub global_y: f64,
    /// The screen the cursor was last on.
    pub current_screen_id: u8,
    /// Total width of all screens.
    total_width: u32,
    /// Maximum height across all screens.
    max_height: u32,
}

impl VirtualCursor {
    /// Create a new virtual cursor at the center of the server screen.
    pub fn new(server_width: u32, server_height: u32) -> Self {
        Self {
            global_x: (server_width / 2) as f64,
            global_y: (server_height / 2) as f64,
            current_screen_id: 0, // Server screen
            total_width: server_width,
            max_height: server_height,
        }
    }

    /// Update the total coordinate system dimensions when screens are added/removed.
    pub fn update_bounds(&mut self, coord: &CoordinateSystem) {
        self.total_width = coord.total_width();
        self.max_height = coord
            .screens
            .iter()
            .map(|s| s.height)
            .max()
            .unwrap_or(1080);
    }

    /// Apply a mouse delta to the virtual cursor position.
    /// Returns the new screen ID if the cursor crossed a boundary.
    pub fn apply_delta(
        &mut self,
        dx: f64,
        dy: f64,
        coord: &CoordinateSystem,
    ) -> Option<BoundaryEvent> {
        // Update position
        self.global_x += dx;
        self.global_y += dy;

        // Clamp to global bounds
        if self.global_x < 0.0 {
            self.global_x = 0.0;
        }
        if self.global_x >= self.total_width as f64 {
            self.global_x = (self.total_width - 1) as f64;
        }
        if self.global_y < 0.0 {
            self.global_y = 0.0;
        }
        if self.global_y >= self.max_height as f64 {
            self.global_y = (self.max_height - 1) as f64;
        }

        // Check which screen the cursor is on
        let new_screen_id = coord
            .screen_at_x(self.global_x as f32)
            .map(|s| s.id)
            .unwrap_or(0);

        // Detect boundary crossing
        if new_screen_id != self.current_screen_id {
            let old_screen_id = self.current_screen_id;
            self.current_screen_id = new_screen_id;

            // Calculate local coordinates on the new screen
            let new_screen = coord.screens.iter().find(|s| s.id == new_screen_id);
            if let Some(screen) = new_screen {
                let local_x = self.global_x as f32 - screen.offset_x as f32;
                let local_y = self.global_y as f32;

                if new_screen_id == 0 {
                    // Returning to server screen
                    Some(BoundaryEvent::Leave {
                        source_screen: old_screen_id,
                    })
                } else {
                    // Entering a client screen
                    Some(BoundaryEvent::Enter {
                        target_screen: new_screen_id,
                        enter_x: local_x,
                        enter_y: local_y,
                    })
                }
            } else {
                None
            }
        } else {
            None
        }
    }

    /// Get the screen info for the current cursor position.
    pub fn current_screen<'a>(&self, coord: &'a CoordinateSystem) -> Option<&'a ScreenInfo> {
        coord.screen_at_x(self.global_x as f32)
    }

    /// Set the cursor position explicitly (e.g., when receiving BoundaryEnter).
    pub fn set_position(&mut self, global_x: f64, global_y: f64) {
        self.global_x = global_x;
        self.global_y = global_y;
    }

    /// Get the local coordinates on the current screen.
    pub fn local_position(&self, coord: &CoordinateSystem) -> (f32, f32) {
        if let Some(screen) = coord.screen_at_x(self.global_x as f32) {
            (
                self.global_x as f32 - screen.offset_x as f32,
                self.global_y as f32,
            )
        } else {
            (self.global_x as f32, self.global_y as f32)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_virtual_cursor_delta() {
        let mut coord = CoordinateSystem::new(1920, 1080);
        coord.add_screen(1, "client".to_string(), 1920, 1080);

        let mut cursor = VirtualCursor::new(1920, 1080);
        cursor.update_bounds(&coord);

        // Start at center of server screen
        assert_eq!(cursor.global_x, 960.0);
        assert_eq!(cursor.current_screen_id, 0);

        // Move right by 500 pixels
        let event = cursor.apply_delta(500.0, 0.0, &coord);
        assert!(event.is_none()); // Still on server screen
        assert_eq!(cursor.global_x, 1460.0);
        assert_eq!(cursor.current_screen_id, 0);

        // Move right by 500 more pixels - should cross boundary
        let event = cursor.apply_delta(500.0, 0.0, &coord);
        assert!(event.is_some());
        match event.unwrap() {
            BoundaryEvent::Enter {
                target_screen,
                enter_x,
                ..
            } => {
                assert_eq!(target_screen, 1);
                assert!(enter_x > 0.0); // Should be past the boundary zone
            }
            _ => panic!("Expected Enter event"),
        }
        assert_eq!(cursor.current_screen_id, 1);

        // Move left by 2000 pixels - should return to server
        let event = cursor.apply_delta(-2000.0, 0.0, &coord);
        assert!(event.is_some());
        match event.unwrap() {
            BoundaryEvent::Leave { source_screen } => {
                assert_eq!(source_screen, 1);
            }
            _ => panic!("Expected Leave event"),
        }
        assert_eq!(cursor.current_screen_id, 0);
    }

    #[test]
    fn test_virtual_cursor_clamp() {
        let coord = CoordinateSystem::new(1920, 1080);
        let mut cursor = VirtualCursor::new(1920, 1080);

        // Move way past the edge
        cursor.apply_delta(5000.0, 0.0, &coord);
        assert!(cursor.global_x < 1920.0); // Should be clamped

        // Move way past the left edge
        cursor.apply_delta(-10000.0, 0.0, &coord);
        assert!(cursor.global_x >= 0.0); // Should be clamped
    }
}
